### ISSUE TITLE
Agda development status

### ISSUE THREAD

**Issue by ajrouvoet** [np/names-for-free#4]
With interest I'm currently reading the names-for-free paper. I've been writing some encodings using PHOAS in Agda and want to compare those to the encoding that you are proposing. As such I was happy to see some agda developments in this repository. 

It's hard to tell however what the status of these developments are. Some of them seem to have been abandoned halfway. Would you mind providing some insight into what has been attempted and possibly what issues halted developments at the time?

**Comment by jyp** [comment]
I'm afraid that I have not looked at this development for several years and
thus I can hardly help: I think that your judgement is as good as mine.

**Comment by ajrouvoet** [comment]
Okay. Thanks for taking the time to answer my question.
